/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Luksev(props) {
  const { nodes, materials } = useGLTF("./models/luksev.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["concrete.001"]}
        position={[-1.768, -0.276, -0.646]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials.concrete}
        position={[-1.468, 1.21, -0.59]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[-1.768, 3.074, -0.646]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.concrete}
        position={[1.8, 1.399, 0.275]}
      />
      <group position={[-1.847, 2.824, -0.765]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube045_2.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={materials["concrete.001"]}
        position={[-1.828, -0.151, -0.591]}
        scale={[1, 0.667, 1]}
      />
      <group position={[-4.45, 2.795, 1.967]} scale={[2.043, 1, 2.043]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={nodes.Cylinder009_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["laca cinza.001"]}
        position={[-2.917, 0.875, -0.947]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials["metal.002"]}
        position={[2.16, 1.099, -0.811]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["madeira.003"]}
        position={[-2.917, 0.875, -0.947]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["tecido 1.001"]}
        position={[-0.05, -0.033, -0.033]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["tecido 1.001"]}
        position={[-1.017, -0.033, -0.125]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["tecido 1.001"]}
        position={[1.133, -0.029, 0.395]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["tecido 1.001"]}
        position={[-0.05, 0.092, -0.547]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["tecido 1.001"]}
        position={[0.95, 0.092, -0.547]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["tecido 1.001"]}
        position={[1.623, 0.042, -0.158]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["tecido 1.001"]}
        position={[0.439, 0.093, -0.003]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["tecido 1.001"]}
        position={[0.409, 0.398, -0.325]}
        rotation={[-0.352, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["tecido 1.003"]}
        position={[0.072, 0.347, -0.139]}
        rotation={[-0.352, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["tecido 1.003"]}
        position={[0.843, 0.348, -0.15]}
        rotation={[-0.352, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["tecido 1.003"]}
        position={[1.399, 0.346, -0.009]}
        rotation={[-Math.PI / 2, -1.219, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials["tecido 1.003"]}
        position={[0.439, 0.365, -0.161]}
        rotation={[-0.352, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__555717"].geometry}
        material={materials["tecido 1.003"]}
        position={[1.977, 1.077, -0.927]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={[-1.203, -1.571, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__556050"].geometry}
        material={materials.tranlucente}
        position={[1.911, -0.144, 0.431]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={[-1.345, -0.635, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__555717001"].geometry}
        material={materials["tecido 1.003"]}
        position={[1.963, 1.077, 1.626]}
        rotation={[-Math.PI, -Math.PI / 2, 0]}
        scale={[-0.849, -1.571, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__556050001"].geometry}
        material={materials.tranlucente}
        position={[1.906, -0.144, 1.335]}
        rotation={[-Math.PI, 1.571, 0]}
        scale={[-1.274, -0.635, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__555717002"].geometry}
        material={materials["tecido 1.003"]}
        position={[1.954, 1.077, -3.135]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={[-1.133, -1.571, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["G-__556050002"].geometry}
        material={materials.tranlucente}
        position={[1.911, -0.144, -1.893]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={[-1.133, -0.635, -0.509]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["madeira.003"]}
        position={[0.202, 1.474, -3.54]}
      />
      <group
        position={[6.335, 0.386, -1.183]}
        rotation={[0, Math.PI / 6, 0]}
        scale={0.01}
      >
        <group
          position={[-551.675, 1.561, -509.076]}
          rotation={[0, -0.262, 0]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
        <group
          position={[-489.76, 1.561, -473.311]}
          rotation={[0, -0.436, 0]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
        <group
          position={[-425.796, 1.561, -434.785]}
          rotation={[0, -Math.PI / 4, 0]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
        <group
          position={[-498.222, 1.561, -312.566]}
          rotation={[-Math.PI, 0.262, -Math.PI]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
        <group
          position={[-567.535, 1.561, -345.4]}
          rotation={[-Math.PI, 0.611, -Math.PI]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
        <group
          position={[-666.281, 1.561, -386.473]}
          rotation={[-Math.PI, 1.309, -Math.PI]}
          scale={[0.893, 0.974, 0.908]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009.geometry}
            material={materials["tecido 1.003"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_1.geometry}
            material={materials["madeira.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_2.geometry}
            material={materials["madeira.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh009_3.geometry}
            material={materials["cassina-luisa-screws"]}
          />
        </group>
      </group>
      <group position={[-0.467, -0.039, 1.2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_1.geometry}
          material={materials["concrete.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube031_2.geometry}
          material={materials.madeira}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["concrete.005"]}
        position={[0.158, -0.195, 0.931]}
      />
      <group position={[-0.461, 0.442, 2.17]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058.geometry}
          material={materials["laca cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_1.geometry}
          material={materials["concrete.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_2.geometry}
          material={materials.marmore}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_3.geometry}
          material={materials.eissivo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube058_4.geometry}
          material={materials.madeira}
        />
      </group>
      <group position={[-0.05, 1.228, 2.279]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={materials["vidro preto.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={materials["vidro preto.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials.madeira}
        position={[-0.35, 0.539, -2.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.madeira}
        position={[-0.325, 0.164, -2.1]}
      />
      <group
        position={[-0.33, 1.861, -2.095]}
        rotation={[0, Math.PI / 6, 0]}
        scale={[0.01, 0.45, 0.01]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.porcelana}
        position={[-0.504, 0.622, -2.1]}
        scale={[1, 0.201, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials["concrete.002"]}
        position={[-0.293, 0.575, -1.951]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["concrete.002"]}
        position={[-0.275, 0.575, -2.125]}
      />
      <group
        position={[-3.143, 1.861, 0.358]}
        rotation={[0, -Math.PI / 3, 0]}
        scale={[0.01, 0.45, 0.01]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials.marmore}
        position={[-3.43, 0.242, 0.375]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["laca cinza"]}
        position={[-5.02, 0.289, 0.375]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["laca cinza"]}
        position={[-5.114, 0.988, -0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["laca cinza"]}
        position={[-5.086, 2.309, 0.363]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.marmore}
        position={[-5.212, 0.808, 0.375]}
      />
      <group position={[-3.367, 0.238, 0.372]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051.geometry}
          material={materials["laca cinza"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube051_1.geometry}
          material={materials.eissivo}
        />
      </group>
      <group position={[-5.418, 1.399, 0.375]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052.geometry}
          material={materials.madeira}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube052_1.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials["laca cinza"]}
        position={[-3.893, 0.289, 0.375]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <group position={[-3.625, -0.141, 0.375]} rotation={[0, 0, -Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054.geometry}
          material={nodes.Cube054.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube054_1.geometry}
          material={nodes.Cube054_1.material}
        />
      </group>
      <group position={[-4.959, 0.976, -0.95]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_1.geometry}
          material={materials["vidro preto"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_2.geometry}
          material={materials["metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_3.geometry}
          material={materials["vidro preto.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube055_4.geometry}
          material={materials.eissivo}
        />
      </group>
      <group position={[-4.961, 1.394, -1.023]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_1.geometry}
          material={materials["vidro preto"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_2.geometry}
          material={materials["vidro preto.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_3.geometry}
          material={materials["metal.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_4.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={materials["vidro preto"]}
        position={[-3.646, 0.701, 0.375]}
      />
      <group position={[-5.227, 0.585, 0.375]} scale={[1.089, 1, 1.05]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063.geometry}
          material={materials.porcelana}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube063_1.geometry}
          material={materials.metal}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube045.geometry}
        material={materials.metal}
        position={[-5.43, 0.982, 0.368]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube046.geometry}
        material={materials["madeira.001"]}
        position={[-5.591, 0.894, 1.161]}
        rotation={[0, 0, 0.175]}
        scale={[1.722, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube047.geometry}
        material={materials["madeira.002"]}
        position={[-5.58, 0.921, 1.025]}
        rotation={[0, 0, 0.175]}
        scale={[1.722, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube048.geometry}
        material={materials.porcelana}
        position={[-5.526, 0.814, -0.461]}
        rotation={[0, -0.262, 0]}
      />
      <group position={[-3.65, 1.739, 0.375]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.eissivo}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[-3.136, 0.727, -0.253]}
      />
      <group position={[-2.925, 0.445, 0.975]} rotation={[0, 1.134, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={materials["madeira.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={materials["madeira.001"]}
        />
      </group>
      <group
        position={[-3.009, 0.445, 0.385]}
        rotation={[-Math.PI, 1.484, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={materials["madeira.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={materials["madeira.001"]}
        />
      </group>
      <group position={[-2.837, 0.445, -0.293]} rotation={[0, -Math.PI / 4, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={materials["madeira.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={materials["madeira.001"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials["concrete.002"]}
        position={[1.261, 0.081, 1.787]}
        rotation={[Math.PI, -1.541, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={materials["concrete.002"]}
        position={[0.929, 0.306, 2.116]}
        rotation={[Math.PI, -1.541, Math.PI]}
        scale={[0.534, 1.799, 0.534]}
      />
    </group>
  );
}

useGLTF.preload("./models/luksev.glb");
